### ISSUE TITLE
Have varlink::generator support i128 integers

### ISSUE THREAD

**Issue by tasleson** [varlink/rust#10]
The specification states that the `int` size is implementation specific.  Rust supports `i128` ref. https://doc.rust-lang.org/std/primitive.i128.html and it would be good for some use cases to allow the code generation to utilize them instead of `i64`.  Having a way to pass this option to `cargo_build_source` and potentially other future options, would be a useful addition IMHO.

**Comment by haraldh** [comment]
commit  c821fd6fcae3c570689cd4cbd1e0e586dda56073
```rust
    varlink::generator::cargo_build_tosource_options(
        "src/io.systemd.network.varlink",
        true,
        &varlink::generator::GeneratorOptions {
            int_type: Some("i128"),
            ..Default::default()
        },
    );
```

Although for serde_json < v1.0.23
serde_json::to_value() returns Error: "i128 is not supported"
