### ISSUE TITLE
Inability to use `handle` in all server implementations

### ISSUE THREAD

**Issue by tasleson** [varlink/rust#11]
The comment:

```rust
impl ConnectionHandler for VarlinkService {
    /// Handles incoming varlink messages from `reader` and sends the reply on `writer`.
    ///
    /// This method can be used to implement your own server.
    fn handle(&self, bufreader: &mut BufRead, writer: &mut Write) -> Result<()> {
```
seems to imply that the `handle` method can be used to implement your own server.  However if a user wants to implement a server using a single process and multiplex using `poll` with non-blocking sockets, then I don't see how this handle function can accommodate it?

**Comment by haraldh** [comment]
Just pass it one b'\0' ended message in a buf: [u8] with BufReader::new(&mut buf) and let it write to a &'a mut [u8] or Vec<u8>.

**Comment by tasleson** [comment]
I'm not sure how your suggestion helps, can you elaborate a bit please?  

The `handle` function has a loop in it.  If the socket is non-blocking when the `read_until` is called it will raise an IO error that it would block.  This could be handled in the caller, so that can be accounted for.  However, once the socket goes EOF when it gets a 0 byte read, the function will break out of the loop and return an `Ok` result which I suppose could be used for the caller to know that socket went EOF too.  However, the crux seems to be about how to handle when the connection gets upgraded.  This is a stack variable and will be lost between invocations of `handle`.

Additionally, doing all these things from the callers perspective seems a little kludgy.  Perhaps with a few improvements it could accommodate this use case cleaner rather that having the caller to glean what's going on?

see: https://github.com/varlink/rust/pull/12 for example code.

**Comment by haraldh** [comment]
https://github.com/varlink/rust/blob/master/examples/ping/src/main.rs#L117-L253
