### ISSUE TITLE
Question: which license can I use for varlink_grammar.peg

### ISSUE THREAD

**Issue by masatake** [varlink/rust#20]
https://github.com/varlink/rust/blob/master/varlink_parser/src/varlink_grammar.peg

Can I choose one from MIT or APACHE?

**Comment by haraldh** [comment]
yes

**Comment by haraldh** [comment]
oh, btw https://github.com/varlink/rust/blob/master/varlink_parser/src/varlink_grammar.rustpeg is the used grammar which works.. `varlink_grammar.peg` might be a little bit out of sync.. better double check

**Comment by masatake** [comment]
Thank you!

**Comment by haraldh** [comment]
May I ask, what you are trying to do? :smile:

**Comment by masatake** [comment]
Imlementing a varlink parser for Universal-ctags (https://ctags.io) that will have packcc, a peg processor written in C.
