### ISSUE TITLE
Recommended Way to Shutdown Varlink Server?

### ISSUE THREAD

**Issue by zicklag** [varlink/rust#25]
Is there a recommended way to shutdown the Varlink server when it is started with `varlink::listen()`?

I'm sure I could find a way to do it if I implemented the server myself, I was just making sure that there wasn't already a good way to do it.

Specifically I am looking to be able to shutdown the server in response to an RPC call, if that changes anything.

**Comment by zicklag** [comment]
I was thinking about passing in an `Arc<Atomicbool>` to the `listen()` function that when set to `false` would shutdown the server. Pretty much like the [`ctrlc`](https://docs.rs) crate example.

Would you be open to a PR for that?

**Comment by haraldh** [comment]
just return  `Err(varlink::ErrorKind::ConnectionClosed.into())` from an API method

**Comment by haraldh** [comment]
https://github.com/varlink/rust/blob/81463ba8da0bfdc41b624adb53feea22110eaf9a/examples/more/src/main.rs#L163-L166

**Comment by haraldh** [comment]
What do you think about PR #27 ??

**Comment by Gunni** [comment]
The above PR was merged 4 years ago, why is this issue still open?
