### ISSUE TITLE
Please tag v10.0.0

### ISSUE THREAD

**Issue by curiousleo** [varlink/rust#29]
Hi! [According to crates.io](https://crates.io/crates/varlink/10.0.0), v10.0.0 is the latest published version of `varlink`. However, v4.0.0 is the latest tag I could find, and it's also the [latest release tagged on Github](https://github.com/varlink/rust/releases).

It would be great to have tags for later releases to browse the source code of precisely that release. I don't think it's necessary to go through that exercise for old releases, but **for 10.0.0, could you please push a tag for exactly the commit that was published to crates.io?**

**Comment by haraldh** [comment]
tagged 11 ... sorry, somehow lost the 10
