### ISSUE TITLE
Please expand `varlink::ListenConfig` to support socker permission

### ISSUE THREAD

**Issue by cathay4t** [varlink/rust#40]
In order to allowing everyone to talk to varlink socket file, I would like to set the socket file permission to 0666.

The possible ways I found is:
 * Implement `varlink::VarlinkService::handle` by myself.
 * Use `service activator`, still trying, not sure it works or not.

Can you expand `ListenConfig` so that `varlink::listen()` could set it?

**Comment by haraldh** [comment]
https://stackoverflow.com/a/42955529/3977812

**Comment by cathay4t** [comment]
Aha. Thanks for the lighting speed response.
