### ISSUE TITLE
Need more documentation when using without `build.rs`

### ISSUE THREAD

**Issue by cathay4t** [varlink/rust#8]
My project already has output `struct` and `error` defined somewhere with many traits.
Hence using `build.rs` seems not a good idea.

I am hoping you could provide documents explains how to code it from scratch.

Thank you.

**Comment by haraldh** [comment]
Well, it's all about the ```Request``` and ```Reply```. If you can serialize your structs with serde_json to a ```serde_json::Value```, you can work with the pure ```Request```and ```Reply```. Of course that has to map to the varlink interface definition and the varlink protocol.

I would suggest to start with a varlink interface definition, let the generator generate one template and take that as a starting point to adapt to your structs and errors.

```
$ cargo install -f varlink
$ $HOME/.cargo/bin/varlink-rust-generator <varlink_interface_definition_file>  > output.rs
```

Then modify ```output.rs``` to your liking. Of course, you are then less flexibel.

Another approach is to write ```From<T>``` traits for your structs to the generated structs.

May I ask, what your project is?

**Comment by cathay4t** [comment]
Thanks.
It's https://github.com/cathay4t/peripety . I am trying to create varlink interface to allows even query and monitor.

**Comment by cathay4t** [comment]
Thanks. It's `struct StorageEvent` and `enum PeripetyError`.
I am working on a CLI tool for that which could be a good reference on varlink. Will ping you in this issue once done.

BTW: Due to the limitation of error kind counts, error-chain might not be a good choice: https://github.com/rust-lang-nursery/error-chain/issues/117#issue-202872567

**Comment by haraldh** [comment]
Do you think https://github.com/rust-lang-nursery/failure is a good alternative?

**Comment by cathay4t** [comment]
The `peripety` project is not maintained by myself and handed over to RH storage team. 
I have moved to network team which is playing on varlink interface also on my personal project:
https://github.com/cathay4t/zatel

No real code there, but  you idea of amending the generated rs file get the varlink interface up and running.

Thanks and closing issue.
